### ISSUE TITLE
Never Succeed!

### ISSUE THREAD

**Issue by seanloook** [kumina/nagios-plugins-kumina#3]
# ./check_tomcat.pl  -l both -a tomcat
CRITICAL: /status/connector/threadInfo/@currentThreadCount is not numeric /status/connector/threadInfo/@maxThreads is not numeric /status/connector/threadInfo/@currentThreadsBusy is not numeric memory in use 244 MiB (2048 MiB); Warning: No tomcat connectors matched name =~ /-80$/|/status/connector/threadInfo/@currentThreadCount=not_numeric /status/connector/threadInfo/@maxThreads=not_numeric /status/connector/threadInfo/@currentThreadsBusy=not_numeric used=256680768 free=1890802880 max=2147483648

**Comment by timstoop** [comment]
This is fixed now!

**Comment by wimco** [comment]
Hi guys am having the same error. Is an one aware of the solution to this problem
